package data;

/**
 * Holds information needed to create the figures.
 * This class is what's passed to ScriptManager by MainWindow as part of the 
 * figure-creation process. All the information needed by the script must be 
 * contained inside this object. Most of the variable names in this class are 
 * taken directly from the names of the GUI elements on the graphing screen of
 * MainWindow.
 * @author Ian Yocum
 * @date 11/19/2013
 * @copyright United States Department of Agriculture Agricultural Research 
 * Service (US Government Public Domain)
 */
public class GraphObject {
    public boolean allTogether; /*!< True if all stage graphs are in one figure, false if each stage graph is in its own figure. (Ties in with @ref combined)*/
    public String combHigh; /*!< High range for combined graph. */
    public String combLow; /*!< Low range for combined graph. */
    public boolean combined; /*!< True if it should produce a graph of the data plotted against the predicted model line for each stage. */
    public boolean compRaw; /*!< True if the data points should be graphed against the predicted model lines on a single figure. */
    public String compRawhigh; /*!< The high value limit for the figure generated by @ref compRaw. */
    public String compRawlow; /*!< The low value limit for the figure generated by @ref compRaw. */
    public boolean expProp; /*!< True if it should produce a figure containing the predicted proportions for each instar of the organisms. */
    public String expProphigh; /*!< High value limit of the figure produced by @ref expProp. */
    public String expProplow; /*!< Low value limit of the figure produced by @ref expProp. */
    public String imgHeight; /*!< Height in pixels of all produced figures. */
    public String imgWidth; /*!< Width in pixels of all produced figures. */
    public boolean log2d; /*!< True if it should produce a figure showing the 2D logarithm */
    public String log2dinterval; /*!< Interval between samples of the 2D logarithm. */
    public String log2doffset; /*!< Offset of the first 2D logarithm sample. */
    public String log2dsample; /*!< How many samples should be taken of the 2D logarithm. */
    public boolean log3d; /*!< True if it should produce a figure showing the 3D logarithm */
    public String logPdf3DShigh; /*!< High value limit for S-axis on the 3D logarithm graph. */
    public String logPdf3DSlow; /*!< Low value limit for S-axis on the 3D logarithm graph. */
    public String logPdf3DThigh; /*!< High value limit for T-axis on the 3D logarithm graph. */
    public String logPdf3DTlow; /*!< Low value limit for T-axis on the 3D logarithm graph. */
    public String[] organismStageNames; /*!< List of the names used for the stages in the organism. This is copied directly from a DatabaseObject. */
    public String outputLoc; /*!< Place for the R script to output the generated figures, usually in the "./Temp" folder. */

    /**
     *
     */
    public GraphObject() {
        allTogether = false;
        combHigh = "";
        combLow = "";
        combined = false;
        compRaw = false;
        compRawhigh = "";
        compRawlow = "";
        expProp = false;
        expProphigh = "";
        expProplow = "";
        imgHeight = "";
        imgWidth = "";
        log2d = false;
        log2dinterval = "";
        log2doffset = "";
        log2dsample = "";
        log3d = false;
        logPdf3DShigh = "";
        logPdf3DSlow = "";
        logPdf3DThigh = "";
        logPdf3DTlow = "";
        organismStageNames = null;
        outputLoc = "";
    }
}
